RUN apt-get update && \
    apt-get install -y \
      npm  \ git

RUN git clone https://github.com/Harutin1991/temperature-measurement-system-front.git manager \
    npm install \
    cd manager \
    npm run dev
